---
- name: install AWS CLI
  pip:
    executable: "{{ aws_python_pip_bin|default('pip3') }}"
    name: awscli
    extra_args: "{{ '-U' if awscli_state == 'latest' else '' }}"
    state: present

- name: install bash autocompletion for AWS CLI
  lineinfile:
    dest: "/home/{{ item }}/.bashrc"
    line: "complete -C '/usr/local/bin/aws_completer' aws"
  loop: "{{ aws_cli_users }}"
  when: aws_cli_bash_autocompletion|bool

- name: install zsh autocompletion for AWS CLI
  lineinfile:
    dest: "/home/{{ item }}/.zshrc"
    line: "source /usr/local/bin/aws_zsh_completer.sh"
  loop: "{{ aws_cli_users }}"
  when: aws_cli_zsh_autocompletion|bool
